const Ziggy = {
    url: 'http:\/\/localhost:8080',
    port: 8080,
    defaults: {},
    routes: {
        'sanctum.csrf-cookie': { uri: 'sanctum\/csrf-cookie', methods: ['GET', 'HEAD'] },
        'documents.index': { uri: 'api\/documents', methods: ['GET', 'HEAD'] },
        'documents.store': { uri: 'api\/documents', methods: ['POST'] },
        'documents.show': {
            uri: 'api\/documents\/{document}',
            methods: ['GET', 'HEAD'],
            parameters: ['document'],
            bindings: { document: 'id' },
        },
        'documents.update': {
            uri: 'api\/documents\/{document}',
            methods: ['PUT', 'PATCH'],
            parameters: ['document'],
            bindings: { document: 'id' },
        },
        'documents.destroy': {
            uri: 'api\/documents\/{document}',
            methods: ['DELETE'],
            parameters: ['document'],
            bindings: { document: 'id' },
        },
        'notices.index': { uri: 'editais', methods: ['GET', 'HEAD'] },
        'notices.create': { uri: 'editais\/create', methods: ['GET', 'HEAD'] },
        'notices.store': { uri: 'editais', methods: ['POST'] },
        'notices.show': {
            uri: 'editais\/{notice}',
            methods: ['GET', 'HEAD'],
            parameters: ['notice'],
            bindings: { notice: 'id' },
        },
        'notices.edit': { uri: 'editais\/{notice}\/edit', methods: ['GET', 'HEAD'], parameters: ['notice'] },
        'notices.update': {
            uri: 'editais\/{notice}',
            methods: ['PUT', 'PATCH'],
            parameters: ['notice'],
            bindings: { notice: 'id' },
        },
        'notices.destroy': {
            uri: 'editais\/{notice}',
            methods: ['DELETE'],
            parameters: ['notice'],
            bindings: { notice: 'id' },
        },
        'notices.audits': {
            uri: 'editais\/{notice}\/audits',
            methods: ['GET', 'HEAD'],
            parameters: ['notice'],
            bindings: { notice: 'id' },
        },
        'projects.index': { uri: 'projetos', methods: ['GET', 'HEAD'] },
        'projects.create': { uri: 'projetos\/create', methods: ['GET', 'HEAD'] },
        'projects.store': { uri: 'projetos', methods: ['POST'] },
        'projects.show': { uri: 'projetos\/{project}', methods: ['GET', 'HEAD'], parameters: ['project'] },
        'projects.edit': { uri: 'projetos\/{project}\/edit', methods: ['GET', 'HEAD'], parameters: ['project'] },
        'projects.update': { uri: 'projetos\/{project}', methods: ['PUT', 'PATCH'], parameters: ['project'] },
        'projects.destroy': { uri: 'projetos\/{project}', methods: ['DELETE'], parameters: ['project'] },
        'projects.assign-supervisors': { uri: 'projetos\/atribuir-fiscal', methods: ['POST'] },
        'projects.create-ci': { uri: 'projetos\/criar-ci', methods: ['POST'] },
        'documents.download': {
            uri: 'projetos\/documentos\/{document}\/download',
            methods: ['GET', 'HEAD'],
            parameters: ['document'],
            bindings: { document: 'id' },
        },
        'documents.download-zip': { uri: 'projetos\/documentos\/download-zip', methods: ['POST'] },
        'projects.openings.update': {
            uri: 'projetos\/{project}\/abertura\/{opening}\/atualizar',
            methods: ['PATCH'],
            parameters: ['project', 'opening'],
            bindings: { project: 'id', opening: 'id' },
        },
        'projects.stages.return': {
            uri: 'projetos\/{project}\/etapas\/{stage}\/devolver',
            methods: ['POST'],
            parameters: ['project', 'stage'],
            bindings: { project: 'id', stage: 'id' },
        },
        'projects.stages.advance': {
            uri: 'projetos\/{project}\/etapas\/{stage}\/tramitar',
            methods: ['PATCH'],
            parameters: ['project', 'stage'],
            bindings: { project: 'id', stage: 'id' },
        },
        'notices.projects': {
            uri: 'editais\/{notice}\/projetos',
            methods: ['GET', 'HEAD'],
            parameters: ['notice'],
            bindings: { notice: 'id' },
        },
        'notices.projects.show': {
            uri: 'editais\/{notice}\/projetos\/{project}',
            methods: ['GET', 'HEAD'],
            parameters: ['notice', 'project'],
            bindings: { notice: 'id', project: 'id' },
        },
        'notifications.index': { uri: 'notificacoes', methods: ['GET', 'HEAD'] },
        'notifications.unread-count': { uri: 'notificacoes\/nao-lidas', methods: ['GET', 'HEAD'] },
        'notifications.mark-read': { uri: 'notificacoes\/{id}\/ler', methods: ['PATCH'], parameters: ['id'] },
        'notifications.mark-all-read': { uri: 'notificacoes\/ler-todas', methods: ['PATCH'] },
        'legal-analysis.index': {
            uri: 'projetos\/{project}\/analise-juridica',
            methods: ['GET', 'HEAD'],
            parameters: ['project'],
            bindings: { project: 'id' },
        },
        'legal-analysis.files.serve': {
            uri: 'projetos\/{project}\/analise-juridica\/arquivos\/{file}',
            methods: ['GET', 'HEAD'],
            parameters: ['project', 'file'],
            bindings: { project: 'id', file: 'id' },
        },
        'legal-analysis.update-status': {
            uri: 'projetos\/{project}\/analise-juridica\/arquivos\/{file}',
            methods: ['PUT'],
            parameters: ['project', 'file'],
            bindings: { project: 'id', file: 'id' },
        },
        'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'profile', methods: ['PATCH'] },
        'profile.destroy': { uri: 'profile', methods: ['DELETE'] },
        'groups.index': { uri: 'grupos', methods: ['GET', 'HEAD'] },
        'groups.update': { uri: 'grupos', methods: ['PUT'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': {
            uri: 'verify-email\/{id}\/{hash}',
            methods: ['GET', 'HEAD'],
            parameters: ['id', 'hash'],
        },
        'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'password', methods: ['PUT'] },
        logout: { uri: 'logout', methods: ['POST'] },
        'storage.local': {
            uri: 'storage\/{path}',
            methods: ['GET', 'HEAD'],
            wheres: { path: '.*' },
            parameters: ['path'],
        },
        'storage.local.upload': {
            uri: 'storage\/{path}',
            methods: ['PUT'],
            wheres: { path: '.*' },
            parameters: ['path'],
        },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
