name: CICD_HOMOLOG
on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  BUILD:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps: 

      - uses: actions/checkout@v7

      - name: Define SHA curto
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Docker Login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Criação da Imagem docker
        uses: docker/bake-action@v6
        with:
          files: ./docker/production/docker-bake-homolog.hcl
          push: true
          set: |
            *.args.VITE_REVERB_APP_KEY=${{ secrets.VITE_REVERB_APP_KEY }}
            *.args.VITE_REVERB_HOST=${{ secrets.VITE_REVERB_HOST }}
            *.args.VITE_REVERB_PORT=${{ secrets.VITE_REVERB_PORT }}
            *.args.VITE_REVERB_SCHEME=${{ secrets.VITE_REVERB_SCHEME }}
            *.args.SHA_SHORT=${{ steps.vars.outputs.sha_short }}

  DEPLOY:
    needs: BUILD
    runs-on: localhomolog
    steps:
      - name: Pull da imagem do dockerhub
        run: docker pull secultceara/efomento:homolog && docker pull secultceara/efomento-nginx:homolog
      - name: Restart do docker compose para atualizar o container com a nova imagem
        run: cd /srv/docker/efomento && docker compose down && docker compose up -d